# Controller for all 7 joints - added by Matt -----------------------
# See iiwa_stack/iiwa_control/config/iiwa_control.yaml for other options
# That file is loaded by iiwa_control.launch
PositionJointInterface_state_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7